Diverse [Personal] Building Notes for omni-tags

* Initials notes
- faire la liste des mots clefs
- personnal font
- voir après s'il peuvent pas etre parsé, et repertorié à la Eclispe

to use: [[http://www.emacswiki.org/emacs/FixmeMode][FIXMEMODE!!!!]]
see also: [[http://www.emacswiki.org/emacs/RFringe][Rfringe]]
[[http://stackoverflow.com/questions/2242572/emacs-todo-indicator-at-left-side][indicate todo left side]]
>>>SEE >[[http://www.emacswiki.org/emacs/fic-mode.el][FIC-MODE]] --- Show FIXME/TODO/BUG/KLUDGE in special face only in comments and strings
fringe...
[[http://www.emacswiki.org/emacs/AddKeywords][addKeyword]]

[[http://www.emacswiki.org/emacs/FontLockKeywords][fontlock keyword]] >> peut donner différentes couelurs à différentes parties de la regexp
=(REGEXP (N1 FACE1) (N2 FACE2) (N3 FACE3) …)=
Highlight group Ni in REGEXP with FACEi


also: [[https://github.com/nschum/highlight-symbol.el][HIGHLIGHT SYMBOL]] to relocate

Letter: contenus
Caractère spéciaux: urgence

find how to catch the ponctuatino: !!?

mapcar (lambda (mode)
	  (font-lock-add-keywords
	   mode
	   '(("FIXME" 0 'show-paren-mismatch-face)
	     ("\\.\\( \\)\\b" 1 'extra-whitespace-face))))
	'(text-mode latex-mode html-mode emacs-lisp-mode
	  texinfo-mode))
The second REGEXP highlights all single spaces after a point. (I want there to be two spaces unless we’re talking about abbreviations.)

Solution temporaire:>
à transformer petit à petit en *vrai minor mode!*. (intégrer dans meme ficher tag face, et le reste

Nota: bug quand des bout de la regexp pas trouvé:
du coup fait devoir decliner les match, mais sans des ???

Doit utiliser une variable fontlock pour surcharge>>> §PK?

* Refactors
** Faces
- Later: liste: (class clolor) (background dark/light)) (autres propriétés
- maybe backround??
- defconst: -> compil, cf magit
# note: set-line face

# ¤note: §maybe: peut avoir fonction à la place de regexp?

A compiled keywords list starts with t.  It is produced internal by `font-lock-compile-keywords'

;; Note that `defface' will not overwrite any faces declared above via
;; `custom-declare-face'.

# " ... foreground et pas color :facepalm:

Note: pas de defvar nécessaire avec un quote devant le nom de la face.
Si veut utiliser var: defface variable with value is symbol (itself)

** TODO Package
- Update documentation
- Make Readme
- get date.
- get [future] github url

GET GET!!!

* Dilemmas & Ideas

# §see:
Namespace? (for function and var.): ¤maybe: replace ':' with '-' to follow convention?

Variable to handle action/description tag symbol


** Features

*** Templates Keywords

Customize keyword recipes?
maybe defined fragment, components. [pattern + highligh]
-> then will buil all the keyword with it
Sym Name Sep ...

could have a time fragment. [that should be headen]
syntax pour choper la date (serait en non visible??)
utiliser surtout pour les here: fonction pour intégrer, grepper, etc.
*** Outline and placeholder
<¤>.
Navigations keys.

Liens avec register position?

*** Navigation and search

Special keymap on tags?
§dig: [see properties section on elisp doc]
